# Generated by Django 5.1.7 on 2025-03-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('case_document', 'Case Document'), ('client_communication', 'Client Communication'), ('legal_research', 'Legal Research'), ('correspondence', 'Correspondence'), ('task_document', 'Task Document'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
