# Generated by Django 5.1.7 on 2025-03-30 10:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='diary',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firm.calendar'),
        ),
        migrations.AddField(
            model_name='diary',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
        migrations.AlterField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
