# Generated by Django 5.1.7 on 2025-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0003_alter_diary_options_diary_date_diary_related_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
